### PR TITLE
Change Test FCS_CKM.6

### PR DESCRIPTION
**Pull request by yiatsec**
Change to address issue https://github.com/DSC-iTC/cPP/issues/235

### CODE REVIEW

**Comment by woodbe** [comment]
Discussion results:

- Leave current test 1, but make conditional to implementations where keys are directly accessible
- take proposed test 1 and make conditional to implementations where keys are referenced
- Force choice of one of the test types (grouping test 1 and test 2 together for the selection)

Merge at the moment while being aware that updated requirements may come from @JDavid-Thompson and the Crypto WG

**Comment by JDavid-Thompson** [comment]
I don’t know what the objections to my version of FCS_CKM.6 are, other asserting that it is not necessary.

  *   Do you not agree with my interpretation of FDP_RIP.1?
  *   Do you agree with that, but think that wear-leveled flash meets that interpretation?

-Dave

**Comment by JDavid-Thompson** [comment]
Brian,

OK.  Thanks for the clarification.

-Dave

**Comment by jvdsn** [comment]
I don't believe the existing tests should be changed this much to address #235. I opened a new PR #292 with smaller changes.

**Pull request closed without merging**
